---
- name: clone repository
  git:
    repo: https://github.com/zhouqing86/spring-boot-in-action.git
    dest: "{{ app_dir }}"
    refspec: '+refs/pull/*:refs/heads/*'

- name: build apps
  shell: ./gradlew build
  args:
    chdir: "{{ app_dir }}"

- name: create user for this app
  user: name=myapp password={{ myapp_password }}

- name: copy systemd service to system
  become: yes
  template:
    src: spring-boot-in-action.service.j2
    dest: /etc/systemd/system/spring-boot-in-action.service

- name: start app
  shell: systemctl enable spring-boot-in-action.service