---
- name: clone repository
  git:
    repo: https://github.com/zhouqing86/spring-boot-in-action.git
    dest: /home/aicaideren/app
    refspec: '+refs/pull/*:refs/heads/*'

- name: Run apps
  shell: ./gradlew build
  args:
    chdir: /home/aicaideren/app

- name: move war to tomcat directory
  shell: cp -rf build/libs/*.war /opt/tomcat/webapps
  args:
    chdir: /home/aicaideren/app
  notify:
    - reload tomcat