---
- name: install mysql
  become: yes
  become_method: sudo
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - mysql-server-5.7
    - mysql-client-5.7

- name: Install packages required for ansible mysql modules on Ubuntu before 16.04
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
  when: ansible_lsb.major_release|int < 16

- name: Install packages required for ansible mysql modules on Ubuntu 16.04
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - libmysqlclient-dev
  when: ansible_lsb.major_release|int >= 16

- name: Install Python package manager on Ubuntu 16.04
  apt: name=python3-pip state=present
  when: ansible_lsb.major_release|int >= 16

- name: Install the Python package required for ansible MySQL modules on Ubuntu 16.04
  pip: name=mysqlclient
  when: ansible_lsb.major_release|int >= 16

- name: update mysql root password for all root accounts
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create the production database
  become_user: root
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: readinglist
    state: present
  notify:
    - Restart MySQL

- name: create mysql user to visit database
  become_user: root
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: inaction
    password: 123456
    priv: 'readinglist.*:ALL'
    state: present